version: "3.8"

services:

  projeto-usuariosapi-db:
    image: postgres:16
    container_name: usuariosapi-postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: projetousuariosapi
      POSTGRES_USER: usuariosuser
      POSTGRES_PASSWORD: usuariospassword
    volumes:
      - usuariosapi-db-data:/var/lib/postgresql/data
    networks:
      - usuariosapi-network

  projeto-usuariosapi-springboot:
    container_name: usuariosapi-springboot 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - projeto-usuariosapi-db
    environment:
      POSTGRES_DB: projetousuariosapi
      POSTGRES_USER: usuariosuser
      POSTGRES_PASSWORD: usuariospassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://projeto-usuariosapi-db:5432/projetousuariosapi
    restart: always
    networks:
      - usuariosapi-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: usuariosapi-rabbitmq
    ports:
      - "5672:5672"      # Porta para conexão com apps
      - "15672:15672"    # Porta da interface web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - usuariosapi-network

  mailhog:
    image: mailhog/mailhog
    container_name: usuariosapi-mailhog
    ports:
      - "1025:1025"      # Porta SMTP
      - "8025:8025"      # Interface web
    networks:
      - usuariosapi-network

volumes:
  usuariosapi-db-data:

networks:
  usuariosapi-network:
    driver: bridge
